-- 0015_stories_summary.up.sql — live story summary column.
--
-- summary holds the LLM-generated narrative the operator reads
-- instead of raw row + ledger dumps. Regenerated by the summary
-- reviewer (config/reviewers/story_summary.md) on every
-- ledger_append for a story. Persisted on the row so reads stay
-- free.

ALTER TABLE stories
    ADD COLUMN summary            TEXT NOT NULL DEFAULT '',
    ADD COLUMN summary_updated_at TIMESTAMPTZ;
